plugins {
    id 'java'
    id 'maven-publish'
    id 'idea'
}

version = rootProject.mod_version
group = rootProject.mod_group_id

subprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'
    apply plugin: 'idea'

    version = rootProject.mod_version
    group = rootProject.mod_group_id

    base {
        archivesName = "${rootProject.mod_id}-${project.name}"
    }

    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://maven.architectury.dev/' }
        maven { url = 'https://maven.maxhenkel.de/repository/public' }
        maven { url = 'https://repo.plasmoverse.com/releases' }
        mavenCentral()
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
        exclude '**/buildtool/**'
    }

    publishing {
        publications {
            register('mavenJava', MavenPublication) {
                from components.java
            }
        }
        repositories {
            maven {
                url "file://${rootProject.projectDir}/repo"
            }
        }
    }

    idea {
        module {
            downloadSources = true
            downloadJavadoc = true
        }
    }
}

tasks.named('wrapper', Wrapper).configure {
    distributionType = Wrapper.DistributionType.BIN
}